export const MESS_ADD_TO_CART_SUCCESS = 'Mua hàng thành công'
export const MESS_UPDATE_CART_SUCCESS = 'Cập nhật giỏ hàng thành công'
export const MESS_DELETE_CART_ITEM_SUCCESS = 'Đã xóa sản phẩm khỏi giỏ hàng'
export const MESS_CART_EMPTY = 'Chưa có sản phẩm nào trong giỏ hảng'
export const MESS_WELCOME = 'Chào mừng bạn đến với shop online'
